name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 或者是你的默认分支，如master

permissions:
  contents: read
  pages: write
  id-token: write

# 允许一个并发部署
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      # 准备部署文件，只包含 example/index.html 和 dist 目录
      - name: Prepare deployment files
        run: |
          mkdir -p deploy
          cp example/index.html deploy/
          cp -r dist deploy/
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'deploy'  # 只上传包含 index.html 和 dist 的目录
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
